### ISSUE TITLE
Auto-tag not working on tag

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-auto-tag#15]
https://github.com/silverstripe/gha-generate-matrix/actions/runs/6090605007/job/16525768248

Issue is that the github event name should be 'push' not 'tag'

```
on:
  push:
    tags:
      - '*.*.*'
```

`push` is the event, while `tags` is a filter

## PRs
- https://github.com/silverstripe/gha-auto-tag/pull/16
